#!/bin/bash
set -euo pipefail

tar czvf \
  optimal-decisions.tar out/*/linear-general-reward/*/optimal.sexp \
  optimal-decisions.tar out/*/linear-general-reward-without-normalisation/*/optimal.sexp
