#!/bin/bash

set -euo pipefail

exp="$1"

DECAY_FACTORS="0.400000 0.900000 1.000000"  # lasso factor is determined by cross validation. It is, given almost for sure, that smaller lambda values are benefitial
BENEFIT_FUNCTIONS="linear_speedup_over_mean log_speedup_over_mean tanh_speedup_over_mean linear_speedup_over_baseline log_speedup_over_baseline tanh_speedup_over_baseline"

for decay_factor in $DECAY_FACTORS; do
  for benefit_function in $BENEFIT_FUNCTIONS; do
    mkdir -p report_plots/reward_assignment/data/lasso/$exp/decay-$decay_factor-benefit-$benefit_function-lasso-factor-auto/
    cp out-v0-reproduce-relabel/$exp/lasso/decay-$decay_factor-benefit-$benefit_function-lasso-factor-auto/search_log.csv \
      report_plots/reward_assignment/data/lasso/$exp/decay-$decay_factor-benefit-$benefit_function-lasso-factor-auto/
  done 
done
