#!/bin/bash

export OPAMROOT=$HOME/fyp/opam-root/

cd "$(dirname "$0")/../../ocaml/"
mkdir -p ../ocaml-tarballs
git show HEAD | head -n 30
git archive --format tar --prefix ocaml/ HEAD | gzip >../ocaml-tarballs/tarball.tar.gz

opam init -n
opam repo add opam-repo-dev $HOME/fyp/opam-repo-dev
opam update
opam switch system
opam switch remove -y 4.06.0+fyp
opam switch install 4.06.0+fyp
opam switch 4.06.0+fyp
