#!/bin/bash

export OPAMROOT=$HOME/fyp/opam-root/

cd "$(dirname "$0")/../../ocaml/"
mkdir -p ../ocaml-tarballs
git archive --format tar --prefix ocaml/ HEAD | gzip >../ocaml-tarballs/tarball.tar.gz

opam init -n
opam repo add opam-repo-dev $HOME/fyp/opam-repo-dev
opam switch system
opam switch remove -y 4.05.0+fyp

export OCAML_MINE_QUERIES=1
echo "Installing compiler ...."
opam switch install 4.05.0+fyp
opam switch 4.05.0+fyp

echo "Installing opam packages ...."
opam install -y $(cat package_list.txt)
