#!/bin/bash

TMP=$(mktemp)
./_build/default/tools/local_reward_model.exe plots describe-features -filename $1 -feature-version V1 2>/dev/null | head -n1 >$TMP
./_build/default/tools/local_reward_model.exe plots describe-features -filename $1 -feature-version V1 2>/dev/null | tail -n+98 | head -n1 >>$TMP

awk '
{ 
    for (i=1; i<=NF; i++)  {
        a[NR,i] = $i
    }
}
NF>p { p = NF }
END {    
    for(j=1; j<=p; j++) {
        str=a[1,j]
        for(i=2; i<=NR; i++){
            str=str" "a[i,j];
        }
        print str
    }
}' $TMP
